pub struct StateBbox {
    pub code: &'static str,
    pub name: &'static str,
    pub min_lat: f64,
    pub max_lat: f64,
    pub min_lon: f64,
    pub max_lon: f64,
}

pub fn us_states() -> &'static [StateBbox] {
    &[
        StateBbox {
            code: "AL",
            name: "Alabama",
            min_lat: 30.22,
            max_lat: 35.01,
            min_lon: -88.47,
            max_lon: -84.89,
        },
        StateBbox {
            code: "AK",
            name: "Alaska",
            min_lat: 51.21,
            max_lat: 71.39,
            min_lon: -179.15,
            max_lon: -129.98,
        },
        StateBbox {
            code: "AZ",
            name: "Arizona",
            min_lat: 31.33,
            max_lat: 37.00,
            min_lon: -114.81,
            max_lon: -109.04,
        },
        StateBbox {
            code: "AR",
            name: "Arkansas",
            min_lat: 33.00,
            max_lat: 36.50,
            min_lon: -94.62,
            max_lon: -89.64,
        },
        StateBbox {
            code: "CA",
            name: "California",
            min_lat: 32.53,
            max_lat: 42.01,
            min_lon: -124.41,
            max_lon: -114.13,
        },
        StateBbox {
            code: "CO",
            name: "Colorado",
            min_lat: 36.99,
            max_lat: 41.00,
            min_lon: -109.06,
            max_lon: -102.04,
        },
        StateBbox {
            code: "CT",
            name: "Connecticut",
            min_lat: 40.98,
            max_lat: 42.05,
            min_lon: -73.73,
            max_lon: -71.79,
        },
        StateBbox {
            code: "DE",
            name: "Delaware",
            min_lat: 38.45,
            max_lat: 39.84,
            min_lon: -75.79,
            max_lon: -75.05,
        },
        StateBbox {
            code: "FL",
            name: "Florida",
            min_lat: 24.40,
            max_lat: 31.00,
            min_lon: -87.63,
            max_lon: -80.03,
        },
        StateBbox {
            code: "GA",
            name: "Georgia",
            min_lat: 30.36,
            max_lat: 35.00,
            min_lon: -85.61,
            max_lon: -80.84,
        },
        StateBbox {
            code: "HI",
            name: "Hawaii",
            min_lat: 18.91,
            max_lat: 22.24,
            min_lon: -160.24,
            max_lon: -154.81,
        },
        StateBbox {
            code: "ID",
            name: "Idaho",
            min_lat: 41.99,
            max_lat: 49.00,
            min_lon: -117.24,
            max_lon: -111.04,
        },
        StateBbox {
            code: "IL",
            name: "Illinois",
            min_lat: 36.97,
            max_lat: 42.51,
            min_lon: -91.51,
            max_lon: -87.02,
        },
        StateBbox {
            code: "IN",
            name: "Indiana",
            min_lat: 37.77,
            max_lat: 41.76,
            min_lon: -88.10,
            max_lon: -84.78,
        },
        StateBbox {
            code: "IA",
            name: "Iowa",
            min_lat: 40.37,
            max_lat: 43.50,
            min_lon: -96.64,
            max_lon: -90.14,
        },
        StateBbox {
            code: "KS",
            name: "Kansas",
            min_lat: 36.99,
            max_lat: 40.00,
            min_lon: -102.05,
            max_lon: -94.59,
        },
        StateBbox {
            code: "KY",
            name: "Kentucky",
            min_lat: 36.50,
            max_lat: 39.15,
            min_lon: -89.57,
            max_lon: -81.96,
        },
        StateBbox {
            code: "LA",
            name: "Louisiana",
            min_lat: 28.93,
            max_lat: 33.02,
            min_lon: -94.04,
            max_lon: -88.82,
        },
        StateBbox {
            code: "ME",
            name: "Maine",
            min_lat: 43.06,
            max_lat: 47.46,
            min_lon: -71.08,
            max_lon: -66.95,
        },
        StateBbox {
            code: "MD",
            name: "Maryland",
            min_lat: 37.91,
            max_lat: 39.72,
            min_lon: -79.49,
            max_lon: -75.05,
        },
        StateBbox {
            code: "MA",
            name: "Massachusetts",
            min_lat: 41.24,
            max_lat: 42.89,
            min_lon: -73.51,
            max_lon: -69.93,
        },
        StateBbox {
            code: "MI",
            name: "Michigan",
            min_lat: 41.70,
            max_lat: 48.31,
            min_lon: -90.42,
            max_lon: -82.12,
        },
        StateBbox {
            code: "MN",
            name: "Minnesota",
            min_lat: 43.50,
            max_lat: 49.38,
            min_lon: -97.24,
            max_lon: -89.49,
        },
        StateBbox {
            code: "MS",
            name: "Mississippi",
            min_lat: 30.17,
            max_lat: 34.99,
            min_lon: -91.66,
            max_lon: -88.10,
        },
        StateBbox {
            code: "MO",
            name: "Missouri",
            min_lat: 35.99,
            max_lat: 40.61,
            min_lon: -95.77,
            max_lon: -89.10,
        },
        StateBbox {
            code: "MT",
            name: "Montana",
            min_lat: 44.36,
            max_lat: 49.00,
            min_lon: -116.05,
            max_lon: -104.04,
        },
        StateBbox {
            code: "NE",
            name: "Nebraska",
            min_lat: 40.00,
            max_lat: 43.00,
            min_lon: -104.05,
            max_lon: -95.31,
        },
        StateBbox {
            code: "NV",
            name: "Nevada",
            min_lat: 35.00,
            max_lat: 42.00,
            min_lon: -120.01,
            max_lon: -114.04,
        },
        StateBbox {
            code: "NH",
            name: "New Hampshire",
            min_lat: 42.70,
            max_lat: 45.31,
            min_lon: -72.56,
            max_lon: -70.70,
        },
        StateBbox {
            code: "NJ",
            name: "New Jersey",
            min_lat: 38.93,
            max_lat: 41.36,
            min_lon: -75.56,
            max_lon: -73.89,
        },
        StateBbox {
            code: "NM",
            name: "New Mexico",
            min_lat: 31.33,
            max_lat: 37.00,
            min_lon: -109.05,
            max_lon: -103.00,
        },
        StateBbox {
            code: "NY",
            name: "New York",
            min_lat: 40.50,
            max_lat: 45.02,
            min_lon: -79.76,
            max_lon: -71.86,
        },
        StateBbox {
            code: "NC",
            name: "North Carolina",
            min_lat: 33.84,
            max_lat: 36.59,
            min_lon: -84.32,
            max_lon: -75.46,
        },
        StateBbox {
            code: "ND",
            name: "North Dakota",
            min_lat: 45.94,
            max_lat: 49.00,
            min_lon: -104.05,
            max_lon: -96.55,
        },
        StateBbox {
            code: "OH",
            name: "Ohio",
            min_lat: 38.40,
            max_lat: 41.98,
            min_lon: -84.82,
            max_lon: -80.52,
        },
        StateBbox {
            code: "OK",
            name: "Oklahoma",
            min_lat: 33.62,
            max_lat: 37.00,
            min_lon: -103.00,
            max_lon: -94.43,
        },
        StateBbox {
            code: "OR",
            name: "Oregon",
            min_lat: 41.99,
            max_lat: 46.29,
            min_lon: -124.57,
            max_lon: -116.46,
        },
        StateBbox {
            code: "PA",
            name: "Pennsylvania",
            min_lat: 39.72,
            max_lat: 42.27,
            min_lon: -80.52,
            max_lon: -74.69,
        },
        StateBbox {
            code: "RI",
            name: "Rhode Island",
            min_lat: 41.15,
            max_lat: 42.02,
            min_lon: -71.86,
            max_lon: -71.12,
        },
        StateBbox {
            code: "SC",
            name: "South Carolina",
            min_lat: 32.05,
            max_lat: 35.22,
            min_lon: -83.35,
            max_lon: -78.54,
        },
        StateBbox {
            code: "SD",
            name: "South Dakota",
            min_lat: 42.48,
            max_lat: 45.95,
            min_lon: -104.06,
            max_lon: -96.44,
        },
        StateBbox {
            code: "TN",
            name: "Tennessee",
            min_lat: 34.98,
            max_lat: 36.68,
            min_lon: -90.31,
            max_lon: -81.65,
        },
        StateBbox {
            code: "TX",
            name: "Texas",
            min_lat: 25.84,
            max_lat: 36.50,
            min_lon: -106.65,
            max_lon: -93.51,
        },
        StateBbox {
            code: "UT",
            name: "Utah",
            min_lat: 36.99,
            max_lat: 42.00,
            min_lon: -114.05,
            max_lon: -109.04,
        },
        StateBbox {
            code: "VT",
            name: "Vermont",
            min_lat: 42.73,
            max_lat: 45.02,
            min_lon: -73.44,
            max_lon: -71.46,
        },
        StateBbox {
            code: "VA",
            name: "Virginia",
            min_lat: 36.54,
            max_lat: 39.47,
            min_lon: -83.68,
            max_lon: -75.24,
        },
        StateBbox {
            code: "WA",
            name: "Washington",
            min_lat: 45.54,
            max_lat: 49.00,
            min_lon: -124.85,
            max_lon: -116.92,
        },
        StateBbox {
            code: "WV",
            name: "West Virginia",
            min_lat: 37.20,
            max_lat: 40.64,
            min_lon: -82.64,
            max_lon: -77.72,
        },
        StateBbox {
            code: "WI",
            name: "Wisconsin",
            min_lat: 42.49,
            max_lat: 47.08,
            min_lon: -92.89,
            max_lon: -86.25,
        },
        StateBbox {
            code: "WY",
            name: "Wyoming",
            min_lat: 40.99,
            max_lat: 45.01,
            min_lon: -111.06,
            max_lon: -104.05,
        },
        StateBbox {
            code: "DC",
            name: "District of Columbia",
            min_lat: 38.79,
            max_lat: 38.99,
            min_lon: -77.12,
            max_lon: -76.91,
        },
    ]
}

pub fn find_state(code: &str) -> Option<&'static StateBbox> {
    let upper = code.to_uppercase();
    us_states().iter().find(|s| s.code == upper)
}
